# Generated by Django 3.1 on 2020-08-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("word", models.CharField(max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Tr"), ("en", "En")], max_length=2
                    ),
                ),
            ],
            options={"unique_together": {("word",)},},
        ),
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_word",
                        to="wordapp.word",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_word",
                        to="wordapp.word",
                    ),
                ),
            ],
            options={"unique_together": {("source", "target")},},
        ),
    ]
