# Generated by Django 3.1 on 2020-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="language",
            field=models.CharField(
                choices=[("tr", "Turkish"), ("en", "English")], max_length=2
            ),
        ),
    ]
