# Generated by Django 3.1 on 2020-09-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordapp", "0002_auto_20200820_1024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={"ordering": ["created_at"]},
        ),
    ]
