# Generated by Django 3.1 on 2020-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordapp", "0002_auto_20200820_1024"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="known_words",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_known_word",
                to="wordapp.Translate",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="unknown_words",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_unknown_word",
                to="wordapp.Translate",
            ),
        ),
    ]
